service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  # profile: femasters
  region: us-west-1
  stage: dev

plugins:
  - serverless-offline

functions:
  api:
    handler: src/api.handler
    events: 
      - http: GET /api
  todos: 
    handler: src/todos.handler
    events: 
      - http:
          path: /todos
          method: GET
  todo:
    handler: src/todo.handler
    events:
      - http:
          path: /todo/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true
